### ISSUE TITLE
content为json数据的时候会分成两条

### ISSUE THREAD

**Issue by lingdu0001** [ideawu/icomet#52]
我发送的命令为：
curl -v "http://192.168.10.117:8000/push?cname=lingdu&content="{"from":"ss","id":"11"}""

接受的时候变成两个：
msg arrived: Message [type=data, cname=lingdu, seq=1, content=from:ss]
msg arrived: Message [type=data, cname=lingdu, seq=2, content=id:11]

**Comment by ideawu** [comment]
你好, 需要将参数进行 urlencode(), 正确的命令是:

```
curl -v "http://192.168.10.117:8000/push?cname=lingdu&content=%7B%22from%22%3A%22ss%22%2C%22id%22%3A%2211%22%7D"
```

**Comment by lingdu0001** [comment]
@ideawu  果然如此 谢谢！
