### ISSUE TITLE
icomet中文的问题

### ISSUE THREAD

**Issue by lingdu0001** [ideawu/icomet#53]
已经用content= URLEncoder.encode(content,"utf-8");设置过中文,
icomet4j 的源码部分也对应改了
mConn.setRequestProperty("Charset", "utf-8");
reader = new BufferedReader(new InputStreamReader(this.input, "utf-8"));
但是为啥收到的中文还是乱码呢。。。另外用js获取到的也是乱码

**Comment by ideawu** [comment]
请修改你的文本编辑器, 将代码保存为 utf-8.

**Comment by lingdu0001** [comment]
@ideawu 果然好了 谢谢。！
