### ISSUE TITLE
Resource interpreted as Script but transferred with MIME type text/html

### ISSUE THREAD

**Issue by IlyaVorozhbit** [ideawu/icomet#54]
Hi, guys!

Can you answer me, why in each message from server in Chrome console I get this message:

Resource interpreted as Script but transferred with MIME type text/html: "http://site.domain:8100/sub?cb=icomet_cb_0&cname=channel&seq=14&noop=5&token=&_=1431216336135&callback=cb"

And how I can fix it?

Thank you

ps. And can you told me, how I can hide information from http://site.domain:8100/sub?cb=icomet_cb_0&cname=channel&seq=1&noop=0&token=&_=1431217359932&callback=cb

Because if I open that link I see all messages in channel at current session

**Comment by ideawu** [comment]
Hi, you can just ignore this message, it is a warning.

The second qustion, it you don't want someone unauthorized to sub a channel, you should enable auth in icomet.conf:

```
front:
	# none|token
	auth: token
```

And modify your system to work as below:

![The work process of iComet in your system](http://www.ideawu.com/icomet/icomet-workflow.png)

**Comment by IlyaVorozhbit** [comment]
Thank you!
