### ISSUE TITLE
IOS接受到消息的方法里怎么调用不了UIViewController里的其他方法？

### ISSUE THREAD

**Issue by chengsan** [ideawu/icomet#66]
// this function is called in a separated thread, it gets called when receive msg from icomet server
//回调接口
size_t icomet_callback(char *ptr, size_t size, size_t nmemb, void *userdata)
{
    const size_t sizeInBytes = size*nmemb;
    NSData *data = [[NSData alloc] initWithBytes:ptr length:sizeInBytes];
    NSString* s = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
 
    NSLog(@"返回结果:%@", s);
    
    //这里为什么调用不了UIViewController里的其他方法

    return sizeInBytes;
}

**Comment by ideawu** [comment]
注释里已经说非常清楚了, 因为这是单独的线程. 你需要搜索一下iOS多线程相关的资料. 简单点说, 就是要

```
dispatch_async(dispatch_get_main_queue()
```

**Comment by chengsan** [comment]
好的，感谢

**Comment by chengsan** [comment]
能给个简单的事例吗，照你的方法好像不行

**Comment by ideawu** [comment]
你好, 之前回复的方案不完整, 我已经更新了 wiki 中的示例, 你参考示例代码即可: https://github.com/ideawu/icomet/wiki/iComet-for-iOS-App
