### ISSUE TITLE
IOS接受到消息的方法里怎么调用不了UIViewController里的其他方法

### ISSUE THREAD

**Issue by chengsan** [ideawu/icomet#67]
能给个简单的事例吗，照你的方法好像不行
// this function is called in a separated thread, it gets called when receive msg from icomet server
//回调接口
size_t icomet_callback(char *ptr, size_t size, size_t nmemb, void *userdata)
{
    const size_t sizeInBytes = size*nmemb;
    NSData *data = [[NSData alloc] initWithBytes:ptr length:sizeInBytes];
    NSString* s = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
 
    //开启主线程
    dispatch_async(dispatch_get_main_queue(), ^
                   {
                       
                       if([NSThread isMainThread])
                       {
                           NSLog(@"回到主线程");
                       }
                       [self setTextResult:s]; //这句话报self没有定义
                       
                   });

    
    return sizeInBytes;
}

**Comment by ideawu** [comment]
请继续在另一个重复的issue讨论. 我关闭此issue.
