### ISSUE TITLE
Uncaught SyntaxError: Unexpected token :

### ISSUE THREAD

**Issue by IlyaVorozhbit** [ideawu/icomet#80]
Hi all!

What I'm doing wrong: 
I use following code to subscribe:

```
var comet = new iComet({
        channel: 'user_{{\Auth::user()->id}}_feed',
        //signUrl: 'http://127.0.0.1:8000/sign',
        subUrl: '{{env('COMET_URI')}}sub',
        callback: function(content){
            var data = JSON.parse(content);
            ion.sound.play("notify");
            renderNotify("Something...", data.message);

            //$( "#messages" ).prepend( '<div class="message is-primary">'+data.from+': '+data.message+'</div' );
        }
    });
```

But I'm get a following error:

sub?cb=icomet_cb_0&cname=user_2_feed&seq=0&noop=0&token=&&callback=cb&_=1492414964626:1 Uncaught SyntaxError: Unexpected token :

The page content: {"type":"next_seq","cname":"","seq":1,"content":""}

**Comment by ideawu** [comment]
See the source code from your web browser, check if there is html/js syntax error.  And

```&token=&&```

May be the problem.
